spring:
  datasource:
    url: jdbc:mysql://172.16.4.247:6006/micpdb
    username: micp
    password: dbmicp@digitteam@247
    driver-class-name: com.mysql.cj.jdbc.Driver


binlog:
  host: 172.16.4.247
  port: 6006
  username: micp
  password: dbmicp@digitteam@247
  schema: micpdb
  btn: false